config/routes.rb
Codefillet::Application.routes.draw do
  devise_for :admins
  
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  
  get "home/index"
  devise_for :users
  resources :code_fillets do
     collection do
        get 'active'
        get 'my'
     end

  end 
  
  root :to => "home#index"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/code_fillet.rb
class CodeFillet < ActiveRecord::Base
    has_many :code_tags
    has_many :tags, :through =>:code_tags

    include PublicActivity::Model
    tracked


	has_many :snippets
#	has_many :votes

	belongs_to :user

	validates :name, length: {minimum: 4}



end

app/models/code_tag.rb
class CodeTag < ActiveRecord::Base
  belongs_to :code_fillet
  belongs_to :tag
end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
  belongs_to :code_fillet
end

app/models/tag.rb
class Tag < ActiveRecord::Base
has_many :code_tags
has_many :code_fillets, :through => :code_tags
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable
  has_many :code_fillets
  #has_many :votes 
  
  validates_presence_of :username
  validates_length_of :username, :minimum=>3

  def unpublished_code_fillets
  	code_fillets.where published: false
  end        
  def unpublished_code_fillets
  	code_fillets.where published: true
  end     

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:username, :email, :password, :remember_me) }
  end

  
end

app/controllers/code_fillets_controller.rb
class CodeFilletsController < ApplicationController
  before_action :authenticate_user! , :only =>[:new,:edit,:my]
  before_action :find_user, :only =>[:new,:create]
  before_action :find_code_fillet, :only =>[:show,:update,:destroy]

  # GET /code_fillets/
  # w przyszlosci GET /code_fillets/?tag=rails => Tag.find(params[:tag]).code_fillets
  def index
  	@code_fillets = CodeFillet.all
  end

  def active
   @code_fillets = CodeFillet.where(active: true)
   render :index
  end
   
  def my
    @code_fillets = current_user.code_fillets
    render :index
  end 


  # GET /code_fillets/:id
  def show
  	tags_ids = CodeTag.where(code_fillet_id: @code_fillet.id).pluck(:tag_id)
    @tags = Tag.where(id: tags_ids).pluck(:name)
  end

  def new
    @code_fillet = CodeFillet.new
  end

  def create
    puts "Ostatnio #{params}" 
    @code_fillet = @user.code_fillets.new permitted_params
    if @code_fillet.save
      #ZAPISALO 
      tag_ids = params[:code_fillet][:tags_ids]
      tag_ids.each do |t|
          @code_fillet.code_tags.create(:tag_id =>t)  unless t.empty?
      end  
      redirect_to @code_fillet
    else
      #NIE ZAPISALO
      render :new
    end
  end

  def edit
    @code_fillet = CodeFillet.find params[:id]
  end

  def update
    @code_fillet.update_attributes permitted_params
    if @code_fillet.save
      redirect_to @code_fillet
    else
      render :new
    end
  end

  def destroy
    @code_fillet.destroy
    redirect_to root_path
  end

  protected
  def permitted_params
    params.require(:code_fillet).permit(:name, :description,:active,:user_id)
  end

  def find_user
     @user = current_user
  end

  def find_code_fillet
    @code_fillet = CodeFillet.find params[:id]
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	activities = PublicActivity::Activity.all
  	@code_fillets = CodeFillet.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/code_fillet_helper.rb
module CodeFilletHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/code_fillets/_form.html.erb
<%= form_for @code_fillet do |f| %>
<% if @code_fillet.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@code_fillet.errors.count, "error") %> prohibited this code fillet from being saved:</h2>

  <ul>
    <% @code_fillet.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>



<div class="field">
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</div>
<div class="field">
  <%= f.label :description %><br>
  <%= f.text_area :description %>
</div>

<div class="field">
  <%= f.label :active %><br>
  <%= f.check_box :active, :checked =>false %>
</div>
</br>

  <% Tag.all.each do |tag| %>
  <%= hidden_field_tag "code_fillet[tags_ids][]", nil %>
  <%= f.label tag.name %>
  <%= check_box_tag "code_fillet[tags_ids][]",tag.id %>
  <% end %>


<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/code_fillets/edit.html.erb
<h1>Edit CodeFillet</h1>


<%= link_to "Browse all CodeFillet's", code_fillets_path %>


<%= render 'form' %>

<%= link_to 'Back', code_fillets_path %>

app/views/code_fillets/index.html.erb
<!DOCTYPE html>
<html>
<head>

	<tittle><h1><%= link_to "Code Fillet", home_index_path %></h1></title> |
		<% if current_user %>
		<%= link_to 'Create new Code Fillet', new_code_fillet_path(@code_fillet) %> 
		<% end %>	

	</head>
	<body>

		<table>
			<thead>
				<th><h2>Name</h2></th>
				<th><h2>Description</h2></th>
				<% if current_user %>
				<th><h2>Active</h2></th>
				<th><h2>Tag</h2></th>
				<th><h2>Action</h2></th>
				<% end %>
			</thead>
			<tbody>

				<% @code_fillets.each do |code_fillet| %>

				<tr>
					<td><%= link_to code_fillet.name, code_fillet_path(code_fillet)%></td>
					<td><%= code_fillet.description%></td>
					
					<% if current_user %>
					<td>
						<% if code_fillet.active? %>
						<%= form_for code_fillet do |f|%>
						<%= f.hidden_field :active, value: false %>
						<%= f.submit "Unpublish"%>
						<% end %>
						<% else%>
						<%= form_for code_fillet do |f|%>
						<%= f.hidden_field :active, value: true %>
						<%= f.submit "Publish"%>
						<% end %>
						<% end%>
					</td>
					<% end %>

					<td> </td>

					<% if current_user %>
					<td><%= link_to "EDIT", edit_code_fillet_path(code_fillet) %></td> |
					<td><%= link_to "DESTROY", code_fillet_path(code_fillet), :confirm => 'Are you sure?', method: :delete %></td>
					<% end %>
				</tr>
			</tr>
			<% end %>
		</tbody>	
	</table>

</body>
</html>

app/views/code_fillets/new.html.erb
<h1>New CodeFillet</h1>

<%= render 'form' %>

<%= link_to 'Back', code_fillets_path %>

app/views/code_fillets/show.html.erb
<tittle><h1><%= link_to "Home Code Fillet's", home_index_path %></h1></title> 

<h1>CODE FILET SHOW</h1>

<h2><%= @code_fillet.name%></h2>
<p><%= @code_fillet.description%></p> 

<h2> Tags: </h2>
<% if @tags.present? %>
<% @tags.each do |tag|  %>
<p>
<%= tag %>
</p>
<% end %>

<% end %>


<% if current_user %>
<%= link_to "Take me to all my CodeFillet's", my_code_fillets_path %> |
<%= link_to "EDIT Code Fillet", edit_code_fillet_path(@code_fillet) %> |
<%= link_to "DESTROY", code_fillet_path(@code_fillet), :confirm => 'Are you sure?', method: :delete %>
<% end %>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>

	<tittle><h1><%= link_to "Code Fillet", home_index_path %></h1></title> 
		<% if current_user %>
		<%= link_to 'Create new CodeFillet', new_code_fillet_path(@code_fillet) %> |
		<%= link_to 'My Code Fillet', my_code_fillets_path(@code_fillet) %>
		<% end %>

	</head>
	<body>
		<table>
			<thead>
				<th><h2>Name</h2></th>
				<th><h2>Description</h2></th>
				<th><h2>Author</h2></th>
			</thead>
			<tbody>

				<% @code_fillets.each do |code_fillet| %>
				<tr>
					<td><%= link_to code_fillet.name, code_fillet_path(code_fillet)%></td>
					<td><%= code_fillet.description%></td>
					<% if code_fillet.user %>
					<td><%= code_fillet.user.username%></td>
					<% else %>
					<td>No user</td>
					<% end %>
				</tr>	
				<% end %>
			</tbody>	
		</table>

	</body>
	</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Codefillet</title>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
	<% if user_signed_in? %>
	You are logged in as <%= current_user.username %>
	<%= link_to "Logout", destroy_user_session_path, method: :delete %>
	<% else %>
	You are not logged in
	<%= link_to "Login", new_user_session_path %>
	<%= link_to "Register", new_user_registration_path %>
	<% end %>

	<%= yield %>

</body>
</html>